// CreateGroup
export const UPDATE_GROUP_NAME = 'UPDATE_GROUP_NAME'
export const UPDATE_GROUP_DETAIL = 'UPDATE_GROUP_DETAIL'
export const UPDATE_GROUP_CATEGORY = 'UPDATE_GROUP_CATEGORY'
export const UPDATE_GROUP_RELATED_GROUPS = 'UPDATE_GROUP_RELATED_GROUPS'
export const UPDATE_GROUP_PRIVATE = 'UPDATE_GROUP_PRIVATE'
export const UPDATE_GROUP_PRIVATE_CONDITIONS = 'UPDATE_GROUP_PRIVATE_CONDITIONS'
export const UPDATE_GROUP_IMG_ONE = 'UPDATE_GROUP_IMG_ONE'
export const UPLOAD_GROUP = 'UPLOAD_GROUP'
export const UPDATE_GROUPS = 'UPDATE_GROUPS'
export const EMPTY_GROUP_INPUTS = 'EMPTY_GROUP_INPUTS'

// Discover
export const POPULATE_GROUPS  = 'POPULATE_GROUPS'

// EditProfile
export const UPDATE_USER = 'UPDATE_USER'
export const UPDATE_USER_SHOP_NAME  = 'UPDATE_USER_SHOP_NAME'
export const UPDATE_USER_SHOP_IMAGE  = 'UPDATE_USER_SHOP_IMAGE'
export const UPDATE_USER_SHOP_DETAIL  = 'UPDATE_USER_SHOP_DETAIL'
export const UPDATE_USER_USERNAME  = 'UPDATE_USER_USERNAME'
export const UPDATE_USER_EMAIL  = 'UPDATE_USER_EMAIL'
export const UPDATE_USER_FULL_NAME  = 'UPDATE_USER_FULL_NAME'
export const UPDATE_USER_FIRST_NAME  = 'UPDATE_USER_FIRST_NAME'
export const UPDATE_USER_LAST_NAME  = 'UPDATE_USER_LAST_NAME'
export const UPDATE_USER_LOCATION  = 'UPDATE_USER_LOCATION'

// Inventory
export const POPULATE_ACTIVE_ITEMS  = 'POPULATE_ACTIVE_ITEMS'

// Group
export const POPULATE_GROUP_ITEMS  = 'POPULATE_GROUP_ITEMS'

// Home
export const POPULATE_HOME_ITEMS  = 'POPULATE_HOME_ITEMS'

// Login
export const ON_LOGGING = 'ON_LOGGING'
export const UPDATE_LOGIN_USERNAME = 'UPDATE_LOGIN_USERNAME'
export const UPDATE_LOGIN_PASSWORD = 'UPDATE_LOGIN_PASSWORD'
export const LOGIN_USER = 'LOGIN_USER'
export const EMPTY_LOGIN_INPUTS = 'EMPTY_LOGIN_INPUTS'

// Register
export const UPDATE_REGISTER_USERNAME = 'UPDATE_REGISTER_USERNAME'
export const UPDATE_REGISTER_EMAIL = 'UPDATE_REGISTER_EMAIL'
export const UPDATE_REGISTER_FIRST_NAME = 'UPDATE_REGISTER_FIRST_NAME'
export const UPDATE_REGISTER_LAST_NAME = 'UPDATE_REGISTER_LAST_NAME'
export const UPDATE_REGISTER_PASSWORD = 'UPDATE_REGISTER_PASSWORD'
export const REGISTER_USER = 'REGISTER_USER'

// Sell
export const UPDATE_ITEM_TITLE = 'UPDATE_ITEM_TITLE'
export const UPDATE_ITEM_BRAND = 'UPDATE_ITEM_BRAND'
export const UPDATE_ITEM_STYLE = 'UPDATE_ITEM_STYLE'
export const UPDATE_ITEM_SIZE = 'UPDATE_ITEM_SIZE'
export const UPDATE_ITEM_DETAIL = 'UPDATE_ITEM_DETAIL'
export const UPDATE_ITEM_CATEGORY = 'UPDATE_ITEM_CATEGORY'
export const UPDATE_ITEM_GROUP = 'UPDATE_ITEM_GROUP'
export const UPDATE_ITEM_QUANTITY = 'UPDATE_ITEM_QUANTITY'
export const UPDATE_ITEM_CONDITION = 'UPDATE_ITEM_CONDITION'
export const UPDATE_ITEM_PRICE = 'UPDATE_ITEM_PRICE'
export const UPDATE_ITEM_ACCEPT_OFFER = 'UPDATE_ITEM_ACCEPT_OFFER'
export const UPDATE_ITEM_LOCATION = 'UPDATE_ITEM_LOCATION'
export const UPDATE_ITEM_MEET_UP = 'UPDATE_ITEM_MEET_UP'
export const UPDATE_ITEM_SHIPPING = 'UPDATE_ITEM_SHIPPING'
export const UPDATE_ITEM_FREE_SHIPPING = 'UPDATE_ITEM_FREE_SHIPPING'
export const UPDATE_ITEM_IMG_ONE = 'UPDATE_ITEM_IMG_ONE'
export const UPDATE_ITEM_IMG_TWO = 'UPDATE_ITEM_IMG_TWO'
export const UPDATE_ITEM_IMG_THREE = 'UPDATE_ITEM_IMG_THREE'
export const UPLOAD_ITEM = 'UPLOAD_ITEM'
export const UPDATE_ITEMS = 'UPDATE_ITEMS'
export const EMPTY_ITEM_INPUTS = 'EMPTY_ITEM_INPUTS'

// Shop
export const POPULATE_SHOP_ITEMS  = 'POPULATE_SHOP_ITEMS'
