//Login
export const ON_LOGGING = 'ON_LOGGING'
export const UPDATE_LOGIN_USERNAME = 'UPDATE_LOGIN_USERNAME'
export const UPDATE_LOGIN_PASSWORD = 'UPDATE_LOGIN_PASSWORD'

//Register
export const UPDATE_REGISTER_USERNAME = 'UPDATE_REGISTER_USERNAME'
export const UPDATE_REGISTER_EMAIL = 'UPDATE_REGISTER_EMAIL'
export const UPDATE_REGISTER_FIRST_NAME = 'UPDATE_REGISTER_FIRST_NAME'
export const UPDATE_REGISTER_LAST_NAME = 'UPDATE_REGISTER_LAST_NAME'
export const UPDATE_REGISTER_PASSWORD = 'UPDATE_REGISTER_PASSWORD'
export const REGISTER_USER = 'REGISTER_USER'
